Entry user
s-nakajima2/be-finaltask pull request #2
Opened 2021-03-10 04:51 UTC by s-nakajima2

ユーザー登録機能

2021-03-10 14:21 UTC, Akinori13 requested changes
確認と修正お願いします。

2021-03-10 14:21 UTC, Akinori13 commented on .gitignore
> +*.pyc
gitignoreに載せる情報について、[Django girlsのチュートリアル](https://tutorial.djangogirls.org/ja/deploy/)を見てみましょう。
ちなみにgitignoreはすでにコミットしたものには適用されません。どうすればよいかは[こちらから](https://qiita.com/yuuAn/items/b1d1df2e810fd6b92574)調べてみてください。そして最後にpushしてください。

2021-03-10 14:21 UTC, Akinori13 commented on pjt00/tclone/templates/tclone/entryconf.html
> +    <a href="../entry">修正</a>
URLテンプレートタグを使ってみましょう

2021-03-10 14:21 UTC, Akinori13 commented on pjt00/tclone/views.py
> +class EntryUser(FormView):
Class-based views（汎用ビュー）の名前は慣習的に「~View」です。（クラス名の名前衝突を避ける目的もあるようです。）

2021-03-10 14:21 UTC, Akinori13 commented on pjt00/tclone/views.py
> +        print(status)
`print(status)`を消しちゃいましょう。

2021-03-10 14:21 UTC, Akinori13 commented on pjt00/tclone/templates/tclone/entryconf.html
> +{% extends "tclone/base.html" %}
ファイル名について。
"conf"だと設定"configuration"の省略だと思うレビュアーもいるかもしれません。（実際設定ファイルの拡張子の一つは「.conf」です。）
なのでここでは「confirm」を使っておきましょう。

2021-03-10 14:21 UTC, Akinori13 commented on pjt00/tclone/views.py
> +from django.template import loader
見たところ使ってないの`loader`は消しちゃいましょう。

2021-03-10 15:03 UTC, s-nakajima2 commented on pjt00/tclone/views.py
> +from django.template import loader
**0.1.1**で修正しました。消し忘れのようです。

2021-03-10 15:04 UTC, s-nakajima2 commented on pjt00/tclone/views.py
> +        print(status)
**0.1.1**で修正しました。消し忘れのようです。

2021-03-10 15:07 UTC, Snak0201 commented on .gitignore
> +*.pyc
**0.1.2**でファイルを修正し、**0.1.3**で該当ファイル( pyc や db )をまとめてはじきました。.gitignoreの存在自体忘れていたのですが、先に書いておくべきでした。

2021-03-11 01:03 UTC, s-nakajima2 commented on pjt00/tclone/templates/tclone/entryconf.html
> +{% extends "tclone/base.html" %}
**0.1.4**で修正しました。名前を付けるときはなるべく略さない方が良いのでしょうか？

2021-03-11 01:05 UTC, s-nakajima2 commented on pjt00/tclone/views.py
> +class EntryUser(FormView):
**0.1.5**で修正しました。今後汎用ビューには"-View"とつけることにします。

2021-03-11 01:08 UTC, s-nakajima2 commented on pjt00/tclone/templates/tclone/entryconf.html
> +    <a href="../entry">修正</a>
**0.1.6**で修正しました。entryok と top の a タグもURLタグに変更しました。

2021-03-11 03:59 UTC, Akinori13 commented on pjt00/tclone/templates/tclone/entryconf.html
> +{% extends "tclone/base.html" %}
一般的に理解できる範囲内であれば、省略して大丈夫です。

2021-03-11 04:45 UTC, s-nakajima2 commented on pjt00/tclone/templates/tclone/entryconf.html
> +{% extends "tclone/base.html" %}
分かりました。慣れるまではあまりにも長いものを除いて省略せずに書いてみることにします。

2021-03-11 04:58 UTC, Akinori13 approved these changes

2021-03-11 04:58 UTC, merged