Log in
s-nakajima2/be-finaltask pull request #3
Opened 2021-03-12 14:29 UTC by s-nakajima2

PULL REQUEST: LOG IN(1.1.0)

2021-03-13 12:15 UTC, Akinori13 requested changes
認証システムについて、[こちら](https://docs.djangoproject.com/en/3.1/topics/auth/default/#module-django.contrib.auth.views)を再度確認してみてください。
不明な点があれば、Discordで話しましょう。

2021-03-13 12:15 UTC, Akinori13 commented on pjt00/tclone/urls.py
> +    path('', include('django.contrib.auth.urls'), name='login'),
ここでDjangoが提供する認証システムを読み込んでいます。`name=login`は不要です。

2021-03-13 12:15 UTC, Akinori13 commented on pjt00/tclone/views.py
>  from django.http import HttpResponse
`HttpResponse`は、おそらく使ってないので、消しちゃいましょう。

2021-03-13 12:15 UTC, Akinori13 commented on pjt00/tclone/views.py
> +def login(request):
Djangoの認証システムはViewを提供するので、不要です。
またTemplate先も認証システムにより既定されています。

2021-03-13 12:15 UTC, Akinori13 commented on pjt00/tclone/views.py
> +# def home(request):
このコメントアウトされたコードは消しちゃいましょう。

2021-03-14 07:22 UTC, s-nakajima2 commented on pjt00/tclone/urls.py
> +    path('', include('django.contrib.auth.urls'), name='login'),
**1.1.0**で修正しました。`name = login` は認証システムの中に取り込まれているから不要ということですね。

2021-03-14 07:28 UTC, s-nakajima2 commented
残りの３つはいろいろな方法を試したときの消し忘れなので[**1.1.0**]でまとめて修正しました。
ログイン認証については大体理解したのですが、１つだけ。
公式ドキュメントの調べ方・見方が良くわかりません。この機能つけたいと思ってもどう調べたらいいのかわからないです（いまはGoogleで公式以外のものを調べて、出てきた関数を公式ドキュメントで調べようとしていますが、それでもうまくいかないことが多いです）。

2021-03-14 13:11 UTC, Akinori13 commented on pjt00/tclone/urls.py
> +    path('', include('django.contrib.auth.urls'), name='login'),
はい。`python -c "import django; print(django.__path__)"`を、ターミナルで入力するとDjangoのパスが見れるので、そこから名前空間をたどって実際のソースコードを見れます。
具体的には、Djangoフォルダ->contribフォルダ->authフォルダ->urls.pyの順です。

2021-03-14 13:12 UTC, Akinori13 commented
ある程度調べても分からなければ、質問しましょう。
いくつかの僕の調べ方。
・公式ドキュメントで調べますが、分からなければコードを読む。
・ドキュメントの[ここ](https://docs.djangoproject.com/en/3.1/)で全体像がみれるので、確認する。
・Qiitaなどで調べた場合はいくつかの小問題に分割して考える。Djangoの処理は主にRouting/View/Model/Templateなので、それぞれ考慮してみる。

ですが、分からないところがあれば遠慮なく質問してください。

2021-03-14 13:12 UTC, Akinori13 approved these changes

2021-03-14 13:13 UTC, merged