Log out
s-nakajima2/be-finaltask pull request #4
Opened 2021-03-16 04:09 UTC by s-nakajima2

最終課題＃３：ログアウト

2021-03-16 11:45 UTC, Akinori13 requested changes
いくつかコメントしました。

2021-03-16 11:45 UTC, Akinori13 commented on pjt00/tclone/templates/tclone/base.html
> +          {% if user.is_authenticated is True %}
`if user.is_authenticated`で大丈夫です。
ちなみにBoolean型を返す関数などは、`is~`です。

2021-03-16 11:45 UTC, Akinori13 commented on pjt00/tclone/templates/registration/login.html
> +{% block log %}{% endblock %}
`{% block log %}{% endblock %}`の位置が適切ではないです。

2021-03-16 11:45 UTC, Akinori13 commented on pjt00/tclone/templates/tclone/base.html
> +            <b><a href="{% url 'tclone:login' %}">ログイン</a></b>
bタグの位置

2021-03-16 11:45 UTC, Akinori13 commented on pjt00/tclone/views.py
>  class EntryUserView(FormView):
```python
user = authenticate(
      username=form.cleaned_data['username'],
      password=form.cleaned_data['password1']
 )
```
と記載されていますが、`authenticate()`はUserオブジェクトを返します。この関数は会員登録と同時にログインする場合に用いられます。
ログインは`login(request, user)`を使いますが、そうでなければ消しちゃいましょう。
ログイン機能実装時に見逃していました、すみません。

2021-03-17 01:18 UTC, s-nakajima2 commented on pjt00/tclone/templates/tclone/base.html
> +          {% if user.is_authenticated is True %}
[**2.1.1**]で修正しました。公式ドキュメント(https://djangoproject.jp/doc/ja/1.0/topics/auth.html)によると、`user.is_authenticated`は常に`True`のみを返すようです。ログインしていないとき、`user.is_authenticated`は何も返さないから`else`以下が動くという解釈でよいのでしょうか？

2021-03-17 01:22 UTC, s-nakajima2 commented on pjt00/tclone/templates/registration/login.html
> +{% block log %}{% endblock %}
**[2.1.1]**で修正しました。`{% block content %}`の外に出しました。

2021-03-17 01:26 UTC, s-nakajima2 commented on pjt00/tclone/templates/tclone/base.html
> +            <b><a href="{% url 'tclone:login' %}">ログイン</a></b>
[**2.1.1**]で修正しました。`<b>`の位置を直しましたが、強調を明示する`<em>`を見つけたのでこれに統一し、cssで修飾しました。

2021-03-17 01:28 UTC, s-nakajima2 commented on pjt00/tclone/views.py
>  class EntryUserView(FormView):
[**2.1.2**]で修正しました。登録が完了したら`entry/ok`ページに遷移するので、これには不要でした。

2021-03-17 04:26 UTC, Akinori13 commented on pjt00/tclone/templates/tclone/base.html
> +          {% if user.is_authenticated is True %}
ややこしいですが、ログインしていない場合は、`user`には`AnonymousUser`が入り、`user.is_authenticated`は`False`を返します。（[参照](https://docs.djangoproject.com/en/3.1/ref/contrib/auth/#django.contrib.auth.models.User.is_authenticated)）
実際に
```python
{{ user }}
```
で確認してみてください。

2021-03-17 04:28 UTC, Akinori13 commented on pjt00/tclone/templates/tclone/base.html
> +            <b><a href="{% url 'tclone:login' %}">ログイン</a></b>
強調は`<em>`、`<b>`、`<strong>`を使いますが、単に太字にするだけであればCSSの`font-weight`も使えます。

2021-03-17 04:31 UTC, Akinori13 approved these changes

2021-03-17 04:31 UTC, merged