最終課題④：ツイート機能
s-nakajima2/be-finaltask pull request #5
Opened 2021-03-20 08:21 UTC by s-nakajima2

ツイート機能を追加しました

2021-03-20 13:38 UTC, Akinori13 requested changes
- アカウント作成・ログイン・ログアウト機能のアプリと、ツイート機能のアプリの二つに分けましょう。
- ツイート機能にはCRUD処理ができるように作成してください。
- 使っていないモジュールなどが読み込まれています。VSCodeの拡張機能を使ってもよいと思います。
その上でいくつかコメントします。

2021-03-20 13:38 UTC, Akinori13 commented on pjt00/tclone/models.py
> +    def publish(self):
使ってないので消しちゃいましょう。

2021-03-20 13:38 UTC, Akinori13 commented on pjt00/tclone/templates/tclone/base.html
> +        {% block content %}
base.htmlは可能な範囲で抽象化しておきましょう。
ツイート画面で`<div class="timeline"><div>`がhtml上で存在しています。

2021-03-20 13:38 UTC, Akinori13 commented on pjt00/tclone/templates/tclone/home.html
> +  {% for text in tweets reversed %}
ここは`text`よりも`tweet`の方がベターです。

2021-03-20 13:38 UTC, Akinori13 commented on pjt00/tclone/views.py
> +        text = super().get_context_data(**kwargs)
ここは`text`よりも`context`の方がベターです。

2021-03-20 13:38 UTC, Akinori13 commented on pjt00/tclone/views.py
> +def tweet(request):
Userがログインしていない状態で、tweet画面を見れてしまいます。これを回避するために`@login_required`を使います。
僕もかつてこれについてかなり悩みました。
- クラスベースビュー: `LoginRequiredMixin`
- 関数ベースビュー: `@login_required`

下のコメントを読んでから戻ってきてください。
リクエストメソッドによって分岐させましょう。このままではGetの時もヴァリデーションが働き、最初からエラーが表示されてしまいます。

2021-03-20 13:38 UTC, Akinori13 commented on pjt00/tclone/views.py
> +    else:
ここは消しちゃいましょう。Djangoはエラーがある場合、そのエラーを格納した該当フォームを返します。
以下どのようなことが起こせるか確認です。（Chromeです。）
1. `tclone/home/tweet`でブラウザの開発機能を開きます。
2. textareaの`maxlength`の値を180に変更して180字入力します。
3. 送信します。

else以下がある場合: エラー内容が表示されません。
ない場合: エラーが正しく表示されます。

2021-03-22 09:46 UTC, s-nakajima2 commented on pjt00/tclone/models.py
> +    def publish(self):
[**3.1.1**]で修正しました。消し忘れです。

2021-03-22 09:49 UTC, s-nakajima2 commented on pjt00/tclone/views.py
> +        text = super().get_context_data(**kwargs)
[**3.1.1**]で修正しました。これは`def get_context_data`の中だから`context`のほうが良いのでしょうか？

2021-03-22 09:59 UTC, s-nakajima2 commented on pjt00/tclone/views.py
> +    else:
[**3.1.1**]で修正しました。`if`にはいつも`else`をつける...と考えていました。`else`以下を書かなければdjangoが吐いたエラーを上書きせずに表示できるということですね。

2021-03-22 10:02 UTC, s-nakajima2 commented on pjt00/tclone/templates/tclone/home.html
> +  {% for text in tweets reversed %}
[**3.1.1**]で修正しました。`tweet`・`tweets`が大量に出てきたので少し混乱していました。

2021-03-23 00:15 UTC, s-nakajima2 commented on pjt00/tclone/templates/tclone/base.html
> +        {% block content %}
[**3.1.1**]で修正しました。なるべく`base.html`がコンパクトになるように書くということでしょうか？

2021-03-23 08:41 UTC, Akinori13 commented on pjt00/tclone/views.py
> +    else:
そうです。

2021-03-23 08:41 UTC, Akinori13 commented on pjt00/tclone/views.py
> +        text = super().get_context_data(**kwargs)
はい。

2021-03-23 08:43 UTC, Akinori13 commented on pjt00/tclone/templates/tclone/base.html
> +        {% block content %}
プロジェクトに共通するものは`base.html`に記載すべきですから、必ずしもコンパクトである必要はありません。
また`a.html`は`base_b.html`を、`base_b.html`は`base.html`を継承するという形にすることも可能です。

2021-03-24 04:56 UTC, s-nakajima2 commented on pjt00/tclone/views.py
> +def tweet(request):
[**3.1.2**]で修正しました。ログインしていない場合には`login`ページに遷移します。

2021-03-26 01:26 UTC, s-nakajima2 commented
[**3.1.8**]までで不要なモジュール削除、CRUD(初めて聞いた言葉でした：作って読んで直して消す処理)、別アプリにすることができました。モジュール削除にはAtomのhighlight-selectedを使いました。

2021-03-26 13:38 UTC, Akinori13 requested changes
いくつかコメントしました。

2021-03-26 13:38 UTC, Akinori13 commented on pjt00/tweet/views.py
> +        check = TweetForm(request.POST)
`check`いらないです。

2021-03-26 13:38 UTC, Akinori13 commented on pjt00/tweet/views.py
> +    form = TweetForm(request.POST)
`form =form = TweetForm(request.POST) `の位置は`if request.method == 'POST':`の次の行にしてください。GETの時二回代入されてしまいます。

2021-03-26 13:38 UTC, Akinori13 commented on pjt00/tweet/views.py
> +            return redirect('tweet:home', pk=tweet.pk)
`pk=tweet.pk`は必要ないです。

2021-03-26 13:38 UTC, Akinori13 commented on pjt00/tweet/views.py
> +@require_POST
バックエンドの代わりにフロントエンドだけがバリデーションを行うのは適切ではありません。
別のユーザーがブラウザの開発者ツールで他の人のツイートを削除できてしまいます。
なおデコレータは複数使えます。

2021-03-26 13:39 UTC, Akinori13 commented
今更気づきましたが、`.gitignore`の`myvenv`は`ve0`と書き換えてコミットしてください。そして管理対象から外してコミットしてください。

2021-03-27 01:49 UTC, s-nakajima2 commented on pjt00/tweet/views.py
> +        check = TweetForm(request.POST)
[**3.2.3**]で修正しました。最初に試行錯誤してた時の名残のようです。

2021-03-27 01:55 UTC, s-nakajima2 commented on pjt00/tweet/views.py
> +    form = TweetForm(request.POST)
[**3.2.3**]で修正しました。POSTでないときに`form = TweetForm(request.POST, instance=tweet)` と `form = TweetForm(instance=tweet)` の２つ代入されていました(POSTでないのにPOSTが呼ばれる状況)。普通に動いていたので見落としていました。

2021-03-27 01:57 UTC, s-nakajima2 commented on pjt00/tweet/views.py
> +            return redirect('tweet:home', pk=tweet.pk)
[**3.2.3**]で修正しました。最初`tdetail`ページに遷移させていた時のものが残っていました。

2021-03-27 02:06 UTC, s-nakajima2 commented on pjt00/tweet/views.py
> +@require_POST
[**3.2.3**]で修正しました。 `@permission_required`でバックエンドにもセキュリティを入れました。修正前はアクセスをPOSTに制限して`tdetail`ページでボタンを隠しているだけでした(これは今も残しています)。

2021-03-27 02:11 UTC, s-nakajima2 commented
[**3.2.2**]で`git`の問題を解消しました。開発者ツールおそるべし...

2021-03-27 06:32 UTC, Akinori13 approved these changes

2021-03-27 06:33 UTC, merged