最終課題⑤：フォロー機能
s-nakajima2/be-finaltask pull request #6
Opened 2021-03-30 01:20 UTC by s-nakajima2

Follow

2021-04-06 06:03 UTC, s-nakajima2 commented
[**4.0.9**]まででとりあえずフォロー機能を整備しましたが、アンフォローのほうがうまくいっていません。どうも`FollowView`に問題がありそうな気もしますが... 詰まってしまったのでヒントが欲しいです。

2021-04-06 08:59 UTC, Akinori13 commented
> [**4.0.9**]まででとりあえずフォロー機能を整備しましたが、アンフォローのほうがうまくいっていません。どうも`FollowView`に問題がありそうな気もしますが... 詰まってしまったのでヒントが欲しいです。

DeleteViewは、URLに含まれるPKと、FFモデルのテーブルのレコードのうち、Primary KeyであるIDが一致するものを探します。これはdeleteメソッドが実行される前に行われています。
【現状の具体例】
ユーザー3(ID=3)がユーザー5(ID=5)をフォローする。
（FFテーブルにID=1のレコードが生成。）
ユーザー3(ID=3)がユーザー5(ID=5)をアンフォローしようとする。
（Djangoは、FFテーブルからID=3のレコードを探すが見つからない。）

2021-04-06 14:00 UTC, s-nakajima2 commented
質問の件は、`DeleteView`をつかわずに関数ベースビューにしました。違うIDのデータを探していたとは... 
`delete`メソッドの前で検索フィルタをつける方法があるかはゆっくり調べたいと思います。
つづいて、フォロー機能のレビューをお願いします。

2021-04-07 15:11 UTC, Akinori13 requested changes
いくつかコメントしました。
- 使っていないTemplateは消しちゃってください。

- `followx`よりも理解しやすく命名しましょう。
（多少長くても可読性が高い方が望ましいです。）

2021-04-07 15:11 UTC, Akinori13 commented on pjt00/tclone/forms.py
> +        return user
必要ないなら消しちゃいましょう。

2021-04-07 15:11 UTC, Akinori13 commented on pjt00/tweet/templates/tweet/profile.html
> +  <p>{{ tweet.tweet }}</p>
Tweetモデルの`__str__`メソッドを確認しましょう。
```suggestion
  <p>{{ tweet }}</p>

```

2021-04-08 08:49 UTC, s-nakajima2 commented on pjt00/tclone/forms.py
> +        return user
[**4.0.1**]で修正しました。

2021-04-08 08:53 UTC, s-nakajima2 commented on pjt00/tweet/templates/tweet/profile.html
> +  <p>{{ tweet.tweet }}</p>
[**4.0.2**]で修正しました。`{{ tweet }}`がpythonでいう`str(tweet)`となるから、`def __str__`によって`tweet.tweet`が返ってくるのでこれで良いということでしょうか。

2021-04-09 02:33 UTC, Akinori13 requested changes
いくつかコメントしました。

2021-04-09 02:33 UTC, Akinori13 commented on pjt00/tweet/templates/tweet/profile.html
> +  {% if not ff %}
`ff`がTemplateに渡っていません。

2021-04-09 02:33 UTC, Akinori13 commented on pjt00/tclone/views.py
> +    template_name = 'tweet/profile.html'
```suggestion
    template_name = 'tclone/follow.html'
```
前回のレビュー時に、使っていないTemplateは削除しましょうとお伝えしましたが、follow.htmlを削除してしまうと、エラーメッセージが表示されませんので、残しておいてください。

2021-04-09 02:33 UTC, Akinori13 commented on pjt00/tclone/views.py
> +    followed = get_user_model().objects.get(pk=pk)
このままだとユーザーが存在しない場合、500を返すので、404を返せるようにしましょう。

2021-04-09 02:34 UTC, Akinori13 commented on pjt00/tweet/templates/tweet/profile.html
> +  <p>{{ tweet.tweet }}</p>
そうです。

2021-04-09 12:40 UTC, s-nakajima2 commented on pjt00/tweet/templates/tweet/profile.html
> +  {% if not ff %}
[**4.2.1**]で修正しました。[**4.1.2**]でFF関連の表記を誤って消してしまっていたようです。

2021-04-09 12:42 UTC, s-nakajima2 commented on pjt00/tclone/views.py
> +    followed = get_user_model().objects.get(pk=pk)
[**4.2.2**]で修正しました。`DoesNotExist`で404を返せるように、`get_object_or_404`を使って書き直しました。

2021-04-09 12:55 UTC, s-nakajima2 commented on pjt00/tclone/views.py
> +    template_name = 'tweet/profile.html'
[**4.2.2**]で修正しました。`profile.html`のほうにもフォームがあるのですが、これだとエラーが吐けないのでしょうか？

2021-04-10 08:11 UTC, Akinori13 commented on pjt00/tclone/views.py
> +    template_name = 'tweet/profile.html'
`profile.html`でもエラーの表示はできますが、この時FollowViewから`profile.html`にprofileViewと同じコンテキストを渡せるようにしなければなりません。
また`template_name='tclone/follow.html'`にしてください。
修正する時は、変更箇所が正しく表示されるかの確認をしておきましょう。

2021-04-10 08:54 UTC, s-nakajima2 commented on pjt00/tclone/views.py
> +    template_name = 'tweet/profile.html'
[**4.3.1**]で修正しました。凡ミスです…

2021-04-11 00:52 UTC, Akinori13 approved these changes

2021-04-11 00:52 UTC, merged