最終課題⑥：お気に入り機能
s-nakajima2/be-finaltask pull request #7
Opened 2021-04-20 10:02 UTC by s-nakajima2

Viewをクラスビューで書いているのは意図的です

2021-04-20 12:41 UTC, Akinori13 requested changes
コメントしました。
- branch名は今後は、小文字に統一した方が良いです。
- エラーの表示ができるようにしましょう。

2021-04-20 12:41 UTC, Akinori13 commented on pjt00/tweet/templates/tweet/favorite.html
> +{% endblock %}
改行を入れておいてください。（他のファイルも忘れずに。）

2021-04-20 12:41 UTC, Akinori13 commented on pjt00/tweet/templates/tweet/fdelete.html
> +hoge
`hoge`ではなくエラーを表示できるようにしましょう。

2021-04-20 12:41 UTC, Akinori13 commented on pjt00/tweet/templates/tweet/favorite.html
> +    <input type="submit" value='������'>
文字化けしています。

2021-04-20 14:52 UTC, s-nakajima2 commented on pjt00/tweet/templates/tweet/favorite.html
> +{% endblock %}
[**5.1.1**]で修正しました。なぜ必要なのか調べてみたら、「最後の行の改行コードを持って最後の行ができる」[https://bottoms-programming.com/archives/indent-tab-space-and-new-line.html#toc5](url) という説明が一番納得がいきました。

2021-04-20 14:54 UTC, s-nakajima2 commented on pjt00/tweet/templates/tweet/favorite.html
> +    <input type="submit" value='������'>
[**5.1.3**]で修正しました。エディタを変えたのでそれが原因だと思います（`S-JIS`になってました）。

2021-04-20 14:54 UTC, s-nakajima2 commented on pjt00/tweet/templates/tweet/fdelete.html
> +hoge
[**5.1.2**]で修正しました。ただ、このhtmlファイルは使われていないかもしれないです...

2021-04-23 02:30 UTC, Akinori13 commented on pjt00/tweet/templates/tweet/fdelete.html
> +hoge
OKです。消しちゃってください。

2021-04-23 02:46 UTC, s-nakajima2 commented on pjt00/tweet/templates/tweet/fdelete.html
> +hoge
[**5.2.1**]で消しました。動作に異常はないです。

2021-04-23 03:34 UTC, Akinori13 approved these changes

2021-04-23 03:35 UTC, Akinori13 commented
lgtm

2021-04-23 03:35 UTC, merged